name: sports
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  awesome_dialog: ^3.2.1
  bloc_concurrency: ^0.2.5
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_slider_drawer: ^3.0.2
  flutter_svg_icons: ^0.0.1+4
  get_it: ^8.0.3
  motion_tab_bar: ^2.0.4
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true

  
  assets:
    - assets/lang/
    - assets/images/
    - assets/icons/

  
  fonts:
    - family: cocon-next-arabic
      fonts:
        - asset: assets/fonts/cocon-next-arabic.ttf
    - family: Hacen Beirut
      fonts:
        - asset: assets/fonts/Hacen Beirut.ttf
